USE movies;

SELECT NAME
FROM moviestar
WHERE GENDER = 'F' AND NAME IN 
(SELECT NAME FROM movieexec WHERE NETWORTH > 10000000);

SELECT NAME 
FROM moviestar
WHERE NAME NOT IN (SELECT NAME FROM movieexec);

SELECT TITLE
FROM movie
WHERE LENGTH > 
(SELECT LENGTH FROM movie WHERE TITLE = 'Star Wars');

SELECT TITLE, NAME
FROM movie JOIN movieexec ON `PRODUCERC#` = `CERT#`
WHERE NETWORTH >
(SELECT NETWORTH FROM movieexec WHERE NAME = 'Merv Griffin');