USE movies;

SELECT TITLE as title, NAME as name
FROM movie JOIN movieexec ON `PRODUCERC#` = `CERT#`
WHERE `PRODUCERC#` IN (SELECT `PRODUCERC#` FROM movie WHERE TITLE = 'Star Wars');

SELECT DISTINCT NAME
FROM movieexec 
JOIN movie ON `PRODUCERC#` = `CERT#` 
JOIN starsin ON TITLE = MOVIETITLE
WHERE STARNAME = 'Harrison Ford';

SELECT DISTINCT NAME, STARNAME
FROM studio 
JOIN movie ON NAME = STUDIONAME
JOIN starsin ON TITLE = MOVIETITLE
ORDER BY NAME;

SELECT STARNAME, NETWORTH, TITLE
FROM starsin
JOIN movie ON TITLE = MOVIETITLE
JOIN movieexec ON `PRODUCERC#` = `CERT#`
WHERE NETWORTH >= ALL (SELECT NETWORTH FROM movieexec);

SELECT NAME
FROM moviestar LEFT JOIN starsin ON NAME = STARNAME
WHERE MOVIETITLE IS NULL;