DROP DATABASE IF EXISTS AIR;
CREATE DATABASE AIR;
USE AIR;

CREATE TABLE AIRLINES (
    CODE CHAR(2) PRIMARY KEY NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL
);

CREATE TABLE AIRPORTS (
    CODE CHAR(3) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL
);

CREATE TABLE AIRPLANES (
    CODE CHAR(3) PRIMARY KEY NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    SEATS INT NOT NULL,
    YEAR INT NOT NULL
);

CREATE TABLE FLIGHTS (
    FNUMBER CHAR(10) PRIMARY KEY NOT NULL,
    AIRLINE_OPERATOR CHAR(2) NOT NULL,
    DEP_AIRPORT CHAR(3) NOT NULL,
    ARR_AIRPORT CHAR(3) NOT NULL,
    FLIGHT_TIME TIME NOT NULL,
    FLIGHT_DURATION INT NOT NULL,
    AIRPLANE CHAR(3) NOT NULL,

    FOREIGN KEY (AIRLINE_OPERATOR) REFERENCES AIRLINES(CODE),
    FOREIGN KEY (DEP_AIRPORT) REFERENCES AIRPORTS(CODE),
    FOREIGN KEY (ARR_AIRPORT) REFERENCES AIRPORTS(CODE),
    FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANES(CODE)
);

CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50)
);

CREATE TABLE AGENCIES (
    NAME VARCHAR(100) PRIMARY KEY NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    PHONE VARCHAR(50)
);

CREATE TABLE BOOKINGS (
    CODE CHAR(6) PRIMARY KEY NOT NULL,
    AGENCY VARCHAR(100) NOT NULL,
    AIRLINE_CODE CHAR(2) NOT NULL,
    FLIGHT_NUMBER CHAR(10) NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BOOKINGS_DATE DATE NOT NULL,
    FLIGHT_DATE DATE NOT NULL,
    PRICE DECIMAL(9, 2) NOT NULL,
    STATUS INT NOT NULL,

    FOREIGN KEY (AGENCY) REFERENCES AGENCIES(NAME),
    FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINES(CODE),
    FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHTS(FNUMBER),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);